### ISSUE TITLE
CATEGORY AND DELIVERY METHOD,locationNOT FUNCTIONING

### ISSUE THREAD

**Issue by js4frsh** [GeorgiKeranov/facebook-marketplace-bot#26] opened 2024-01-06 20:59 UTC
Im having issues i believe on east coast is a different lay out 

1) category has sub category for example mattress process
-furniture
-mattresses

so its not typing it so i put miscalaneuos since its the only category without sub category

2+3)the location and delivery method for my layout shows on 2nd page after clicking next so it doesnt catch this function 

anyway i can edit the code to change when it performs this action i dont know how to any advice will be helpful 

![Screenshot (11)](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/75636555/5e4b7c63-d806-48ce-ab0c-b30ee118220d)

**Comment by NikoTumi** [comment] 2024-02-05 22:36
Hi, I am outside of this original program. Its perfectly fine to fork this project and edit the code yourself. I am thinking about adding a tkinter popup window inside a try catch for categories and location selection until the automation is fixed. I've never used scraper, but once I get this implemented, I'll check out how to fix this. Please feel free to do what you can. I'm not sure the owner is actively updating these scripts.

**Comment by GeorgiKeranov** [comment] 2024-02-07 11:32
Hello @js4frsh, please provide the full context so I can reproduce the issue, give me the CSV file that you are trying to upload and it isn't working, for now, I am closing the issue because of a lack of context.

**Closed as completed by GeorgiKeranov** 2024-02-07 11:32 UTC
