### ISSUE TITLE
The bot can't click on publish button

### ISSUE THREAD

**Issue by rajsibt** [GeorgiKeranov/facebook-marketplace-bot#10] opened 2022-12-07 14:13 UTC
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS C:\Users\Haier> python main.py
ERROR: Timed out waiting for the element with css selector "div[aria-label="Marketplace sidebar"] a[aria-label="Create new listing"]" to load

![fbbot issue 2 ](https://user-images.githubusercontent.com/120019898/206200213-26a31663-9f0f-4bd5-b8e3-4b3b97994eec.png)
![fbbot issue](https://user-images.githubusercontent.com/120019898/206200717-63ea52be-98a0-4474-b4b4-2fade8f3ad36.png)

in the 2nd screenshot you can see the publish button get blocked  and cursor changed into disabled pointer ad after waiting some time bot exit

**Comment by GeorgiKeranov** [comment] 2023-01-16 21:54
Yes, the issue is fixed in the last update, please check if you still have any issues :)

**Closed as completed by GeorgiKeranov** 2023-01-16 21:54 UTC
